
---
- name: get config of gig1 and gig2
  hosts: IOS
  connection: local
  vars:
    intf1: GigabitEthernet1
    intf2: GigabitEthernet2

  tasks:
    - name: disable proxy-arp
      ios_command:
        commands:
          - sho run int {{intf1}}
          - sho run int {{intf2}}

      register: intf_out

    - name: print stuff
      debug:
        var: intf_out.stdout_lines
