---
- name: pre-config captures - play-1
  hosts: localhost

  tasks:
    - name: run precheck playbook
      command: ansible-playbook p33-ospf-capture.yml --tags precheck

- name: configure OSPF on both routers - play-2
  import_playbook: p33-ospf-config.yml

- name: post-config captures - play-3
  hosts: localhost

  tasks:
    - pause: seconds=30

    - name: run postcheck playbook
      command: ansible-playbook p33-ospf-capture.yml --tags postcheck

- name: Compare pre and post files and create a diff file - play-4
  hosts: localhost
  connection: local

  tasks:
    - set_fact: TIMESTAMP="{{lookup('pipe','date \"+%Y-%m-%d-%H-%M\"')}}"

    - name: diff pre and post IOS files
      command: diff /home/cisco/p33-precheck-ios-ospf.txt /home/cisco/p33-postcheck-ios-ospf.txt

      register: IOS_DIFF

      failed_when: "IOS_DIFF.rc > 1"

    - name: create diff file with timestamp included in the name
      copy:
        content: "{{ IOS_DIFF.stdout }}"
        dest: "/home/cisco/op33-ios_diff_{{ TIMESTAMP }}.txt"

    - name: diff pre and post XR files
      command: diff /home/cisco/p33-precheck-xr-ospf.txt /home/cisco/p33-postcheck-xr-ospf.txt

      register: XR_DIFF

      failed_when: "XR_DIFF.rc > 1"

    - name: create diff file with timestamp included in the name
      copy:
        content: "{{ XR_DIFF.stdout }}"
        dest: "/home/cisco/op33-xr_diff_{{ TIMESTAMP }}.txt"
